function(configure_defaults)
    set(GLFW_INSTALL OFF CACHE BOOL "GLFW" FORCE)
    set(GLFW_BUILD_DOCS OFF CACHE BOOL "GLFW" FORCE)
    set(GLFW_BUILD_TESTS OFF CACHE BOOL "GLFW" FORCE)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "GLFW" FORCE)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "GLFW" FORCE)
    option(DISARRAY_COMPILE_PROFILE "Compile time profilation" OFF)
    option(DISARRAY_BUILD_TESTS "Build tests" OFF)
    option(DISARRAY_LOG_ALLOCATIONS "Log all allocations" OFF)

    # find_package(OpenMP REQUIRED)
endfunction(configure_defaults)
