name: Clang17 CMake Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  BUILD_TYPE: RelWithDebInfo
  CXX: clang++-17
  CC: clang-17
  NINJA_STATUS: "[%f/%t] %c/s %e "

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wget git cmake -y

      - name: Install LLVM
        run: |
          sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 17 -y

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-12 g++-12 libtbb-dev libxinerama-dev libxcursor-dev
            libxi-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
            libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev
          version: 1.0

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
        with:
          version: 1.11.1
          platform: linux

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-use-cache: true

      - name: Configure CMake
        run: cmake
          -B build
          -D CMAKE_CXX_COMPILER=${{env.CXX}}
          -D CMAKE_C_COMPILER=${{env.CC}}
          -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -G Ninja

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel 20

      - name: Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}
