name: Linting

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wget git cmake -y

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 16 -y

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
