name: Linting

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Early exit
        if: contains(github.event.head_commit.message, 'wip')
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: "."
          extensions: "hpp,cpp"
          clangFormatVersion: 16
